# Generated by Django 3.0.2 on 2020-01-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilisation', models.DateField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_equipements.Equipement')),
            ],
        ),
    ]
